defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_ # keep this to the end of defaults to have config.yaml override values set in other yamls

hydra:
  output_subdir: null
  run:
    dir: .

meta:
  in_file: /home/muneeba/survival_repo/OSST_survival_ML/Data/80_original.xlsx
  test_file: /home/muneeba/survival_repo/OSST_survival_ML/Data/20_original.xlsx
  out_dir: /home/muneeba/survival_repo/OSST_survival_ML/output
  events: "Event"
  times: "Time"
  init_seed: 545
  n_seeds: 1
  n_workers: 24
  plot_format: "png"
  overwrite: True

preprocessing:
  save_as_pickle: True  # save the preprocessed data as pickle file for each seed
  test_size: 0.2
  corr_threshold: 0.9
  replace_zero_time_with: 0.01
  impute_strategy: "median"
  normalisation: "z-score"

survival:
  active: True  # False -> only run preprocessing, i.e. create data splits
  scoring: "as_concordance_index_ipcw_scorer"
  n_cv_splits: 4
  n_iter_search: 5
  search_type:
      SimpleExecution: True
      GridSearch: True
      RandomSearch: False
  scalers:
    StandardScaler: False
    MinMaxScaler: True
    RobustScaler: False
  feature_selectors:
    SelectKBest: True
    VarianceThreshold: False
    FastICA: False
    PCA: False
    KernelPCA: False
    TruncatedSVD: False
  feature_selector_params:
    SelectKBest:
      selector__k: [5, 10, 15]
      #selector__k: [15]
    VarianceThreshold:
      selector__threshold: ${numpy_range:0.01, 0.9, 0.1}
    FastICA: {}
    PCA: {}
    KernelPCA: {}
    TruncatedSVD: {}
  bucketizers:
    2BinBucketizer: True
    3BinBucketizer: False
    4BinBucketizer: False
  models:
    CoxPH: False
    OSST: True
    RSF: False
  model_params:
    CoxPH:
      model__estimator__alpha: [0.0001, 0.001, 0.01, 0.1, 1, 10]
    OSST:
      model__estimator__regularization: [0.1]
      model__estimator__depth_budget: [5]
      model__estimator__minimum_captured_points: [3]
    RSF:
      model__estimator__n_estimators: [50, 100, 200]
      model__estimator__max_depth: [null, 5, 10]
